### ISSUE TITLE
The shadows in Gnome's windows have not been disabled by this exentension.

### ISSUE THREAD

**Issue by slottwo** [CorvetteCole/blur-provider#4]
System information:
OS: Pop!_OS 20.04 LTS x86_64
Kernel: 5.4.0-7642-generic 
Shell: bash 5.0.17 
Resolution: 1368x768 
DE: GNOME 
Theme: Sweet-Dark [GTK2/3] 
Icons: Sweet-Rainbow [GTK2/3] 
GNOME Shell 3.36.4

**Comment by CorvetteCole** [comment]
is this on xorg or wayland?

**Comment by slottwo** [comment]
I can't say, I think it's xorg, because once I tried to install the wayland and failed miserably, I had to build several necessary packages from the source code, and after a week of research and completion I gave up and formatted the PC. However, I did not find any command in the terminal related to x11 or xorg. But I think the answer may be a third one (mixed with the xorg answer): Nvidia X Server 390.138.
I'm a complete noob, I'm sorry

**Comment by slottwo** [comment]
I tried to disable the shadows manually, but the solutions I found on the forums involved editing the file ~/.config/gtk-3.0/gtk.css, but this file not exist. The only items in this directory are bookmarks and settings.ini

**Comment by CorvetteCole** [comment]
The extension should just avoid blurring shadows rather than getting rid of them altogether. Is that the case?

**Comment by slottwo** [comment]
Got it! Before I thought that the extension removed the shadows because of a blur bug that could be the fault of the shadows in gnome.
[blur video.mp4](https://drive.google.com/file/d/1Qi3dNFcBTXHWaVGSorGcRTgc1-m1omRz/view?usp=sharing)
(For some reason, the GIF was larger than the original file and exceeded 10 MB, so I just rerecorded it with "standard" quality and put it in Drive)

**Comment by slottwo** [comment]
Got it! Before I thought that the extension removed the shadows because of a blur bug that could be the fault of the shadows in gnome.
[blur video.mp4](https://drive.google.com/file/d/1sOtg0OEOaV0HASAREsLMe3okqhyc1xoa/view?usp=sharing)
(For some reason, the GIF was larger than the original file and exceeded 10 MB, so I just rerecorded it with "standard" quality and put it in Drive)

**Comment by CorvetteCole** [comment]
The artifacts around where the shadow is when over a blurred window is actually a Gnome bug. View it here: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2857. At the moment, I don't know a workaround for this

**Comment by slottwo** [comment]
Oh, got it. Okay then. I'll wait if they can solve it. Thanks for listening.
