### ISSUE TITLE
Support for Pantheon

### ISSUE THREAD

**Issue by ghost** [CorvetteCole/blur-provider#6]
As far as I'm aware, Pantheon uses Gala as it's window manager, which is a fork of Mutter.
So adding Blur Provider support to Pantheon might be possible.

The desktop environment is widely used on elementary OS, since it's default on there.

**Comment by ghost** [comment]
This should not actually happen, doesn't fit elementary's design

**Comment by CorvetteCole** [comment]
@KorbsStudio This can happen in the new extension perhaps if still desired, I have never used use elementary OS though

**Comment by ghost** [comment]
Blur is not at all supported in their window manager. There have been forks to make it possible, but they seem to break.

**Comment by CorvetteCole** [comment]
ah. Well that handles that pretty well then
